language: objective-c
osx_image: xcode10.2
before_install:
- pod cache clean --all
- pod update
install:
- gem install xcpretty-travis-formatter
script:
  - xcodebuild -workspace 'essentia-network-core-ios.xcworkspace' -scheme 'essentia-network-core-ios' -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.4' | xcpretty -f `xcpretty-travis-formatter`