language: 
  - objective-c
osx_image: 
  - xcode9.4
script:
  - xcodebuild -project 'essentia-network-core-ios.xcodeproj' -scheme 'essentia-network-core-ios' -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.4'